'use client'
import React, { useEffect, useState } from 'react';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.innerHeight = window.innerHeight;
      window.innerWidth = window.innerWidth;
    };
    setIsClient(true);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {isClient && children}
        </body>
    </html>
  )
}
